name: Run Tests
run-name: ${{ gitea.actor }} is running Rails Tests
on: [push, pull_request]

jobs:
  Rails-Tests:
    runs-on: ruby-3.3.7
    steps:
      - name: Check out code
        uses: https://github.com/actions/checkout@v3
      - name: Install dependencies
        run: bundle install
      - name: Precompile assets
        run: rake assets:precompile
      - name: Run tests
        run: bundle exec rails test
